'use client';
import './globals.css';
import { QueryClientProvider, QueryClient } from 'react-query';
import { ReactQueryDevtools } from 'react-query/devtools';
import Nav from './home/page';
export const metadata = {
  title: 'my Training',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <div className="flex flex-row box-border ">
            <div className="basis-0">
              <div className="sticky top-0">
                <Nav />
              </div>
            </div>

            <div className="w-full"> {children}</div>
          </div>
          <ReactQueryDevtools initialIsOpen={false} />
        </QueryClientProvider>
      </body>
    </html>
  );
}
